abrace/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout', views.logout_view, name='logout'),
    path('profile/', views.ProfileDetail.as_view(), name='profile'),
    path('profile/edit', views.ProfileEdit.as_view(), name='profile_edit'),
    path('profile/delete', views.profile_delete, name='profile_delete'),
    path('profile/edit/categories', views.save_categories, name='save_categories'),
    path('profile/projects', views.MyProjectsList.as_view(), name='my_projects'),
    path('profile/reviews', views.review_view, name='profile_reviews'),
    path('profile/view/<str:cpf>/', views.ViewProfile.as_view(), name='view_profile'),
    path('profile/view/<str:cpf>/filter/<str:role>/', views.ViewProfile.as_view(), name='view_profile_projects_filter'),
    path('review/<str:reviewed_pk>/<str:project_pk>', views.ReviewCreateView.as_view(), name='review'),
    path('profile/projects/filter/<str:role>/', views.MyProjectsList.as_view(), name='my_projects_filter'),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.home, name='home'),
    path('projects', views.ProjectsList.as_view(), name='projects'),
    path('filter/category/<str:category>/', views.ProjectsList.as_view(), name='projects_filter'),
    path('project/new', views.ProjectDashboard.as_view(), name='project_new'),
    path('project/edit/categories/set/<str:project_pk>', views.set_categories, name='set_categories'),
    path('project/edit/categories/<str:project_pk>', views.save_categories, name='save_categories'),
    path('project/edit/<str:project_pk>', views.ProjectDashboard.as_view(), name='project_edit'), 
    path('project/detail/<str:project_pk>', views.ProjectDetail.as_view(), name='project_detail'),
    path('project/post/send', views.send_post, name='send_post'),
    path('project/comment/send', views.send_comment, name='send_comment'),
    path('project/post/detail/<str:post_pk>', views.PostDetail.as_view(), name='post_detail'),
    path('project/leave', views.leave_project, name='project_leave'),
    path('project/delete', views.delete_project, name='project_delete'),
    path('project/members/<str:project_pk>', views.MembersList.as_view(), name='members_list'),
    path('project/mod/add', views.add_mod, name='mod_add'),
    path('project/mod/remove', views.remove_mod, name='mod_remove'),
    path('project/member/remove', views.remove_member, name='member_remove'),
    path('project/post/delete', views.delete_post, name='post_delete'),
    path('project/solicitation/add', views.add_solicitation, name='solicitation_add'),
    path('project/solicitation/remove', views.remove_solicitation, name='solicitation_remove'),
    path('project/solicitation/accept', views.accept_solicitation, name='solicitation_accept'),
    path('project/solicitation/reject', views.reject_solicitation, name='solicitation_reject'),
    path('project/solicitation/<str:project_pk>', views.Solicitation.as_view(), name='project_solicitation'),
    path('project/deactivate/<str:project_pk>', views.deactivate, name='deactivate'),
    path('project/search/', views.search_project, name='search_project'),
]

projects/forms/comment.py
from collections import defaultdict
from django.forms import ModelForm
from projects.models import Comment


class CommentForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'class': 'form-control', 'required':'required', 'placeholder': 'Escreva um Comentário...'})
        self._my_errors = defaultdict(list)

    class Meta:
        model = Comment
        fields = [
            'text',
        ]

projects/forms/post.py
from collections import defaultdict
from django.forms import ModelForm
from projects.models import Post


class PostForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'class': 'form-control', 'required':'required', 'placeholder': 'Escreva uma Postagem...'})
        self._my_errors = defaultdict(list)

    class Meta:
        model = Post
        fields = [
            'text',
        ]

projects/forms/project.py
from django import forms
from collections import defaultdict
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from projects.models import Project


class ProjectForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cover_photo'].widget.attrs.update({'class': 'form-control-file d-none', 'id': 'flImage'})
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'required':'required'})
        self.fields['description'].widget.attrs.update({'class': 'form-control', 'required':'required'})
        self._my_errors = defaultdict(list)

    class Meta:
        model = Project
        fields = [
            'cover_photo',
            'name',
            'description',
        ]
        labels = {
            'name': 'Nome *',
            'cover_photo': 'Imagem de capa *',
            'description': 'Descrição *',
        }



    def clean_name(self):
        data = self.cleaned_data.get('name').strip()

        if len(data) < 1:
            raise ValidationError(
                'Este campo não pode estar vazio',
                code='required',
            )

        return data

    def clean_description(self):
        data = self.cleaned_data.get('description')

        if len(data) < 1:
            raise ValidationError(
                'Este campo não pode estar vazio',
                code='required',
            )

        return data


    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)

        if self._my_errors:
            raise ValidationError(self._my_errors)

projects/forms/project_categories.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from accounts.models import Category
from projects.models import Project

class ProjectCategoriesForm(ModelForm):

    categories = forms.ModelMultipleChoiceField(
        queryset=None, 
        label='',
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'category-profile'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categories'] = forms.ModelMultipleChoiceField(
            queryset=Category.objects.all() , 
            widget=forms.SelectMultiple(attrs={'class': 'js-choice form-control'}),
            required=False,
            label='Categorias',
        )

    class Meta:
        model = Project
        fields = [
            'categories',
        ]
        widgets = {
            'categories': forms.SelectMultiple()
        }

projects/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from projects.models import Project, Post, Comment
from projects.forms import ProjectForm, PostForm, CommentForm, ProjectCategoriesForm
from django.urls import reverse
from accounts.models import CustomUser, Category
from django.http import Http404
from django.db.models import Q

@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
)
class ProjectDashboard(View):

    def render_template(self, form, project_pk, form_categories, project_active=False, project_img=False):
        return render(
            self.request,
            'projects/pages/project_dashboard.html',
            context={
                'form': form,
                'project_pk': project_pk,
                'form_categories': form_categories,
                'project_active': project_active,
                'project_img': project_img,
                'return_page': self.get_return_page(),
            }
        )
    
    def get_return_page(self):
        next_param = self.request.GET.get('next', None)
        if not next_param:
            next_param = "/"
        return next_param
    
    def get_project(self, project_pk=None):
        project = None

        if project_pk is not None:
            project = get_object_or_404(Project, composite_pk=project_pk)

        return project

    def get(self, request, project_pk=None):

        project = self.get_project(project_pk)
        form = ProjectForm(instance=project)
        form_categories = None
        project_active = False
        project_img = False

        if project_pk:
            form_categories = ProjectCategoriesForm(instance=project)
            project_active = project.status
            project_img = project.cover_photo

        return self.render_template(form, project_pk, form_categories, project_active, project_img)

    def post(self, request, project_pk=None):

        project = self.get_project(project_pk)

        form = ProjectForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=project, 
        )

        if form.is_valid():

            project = form.save(commit=False)
            owner = CustomUser.objects.get(pk=request.user.pk)
            project.owner = owner

            if not project_pk:
                auto_id = Project.objects.filter(owner=owner)

                if auto_id:
                    project.project_id = auto_id.last().project_id + 1
                else:
                    project.project_id = 0

            project.save()
            
            if project_pk:
                messages.success(request, 'O projeto foi salvo com sucesso!')
                return redirect (reverse('projects:project_detail', args=[project.composite_pk]))
            return redirect (reverse('projects:set_categories', args=[project.composite_pk]))

        project_active = False
        form_categories = None
        project_img = False
        if project_pk:
            form_categories = ProjectCategoriesForm(instance=project)
            project_active = project.status
            project_img = project.cover_photo

        messages.error(request, 'Há campos incorretos no formulário')
        return self.render_template(form, project_pk, form_categories, project_active, project_img)


@login_required(login_url='accounts:login', redirect_field_name='next')    
def save_categories(request, project_pk):
    if not request.POST:
        raise Http404
    
    project = get_object_or_404(Project, composite_pk=project_pk)

    form = ProjectCategoriesForm(data=request.POST or None, instance=project)

    if form.is_valid():
        form.save()
    else:
        project.categories.set('')
        project.save()


    messages.success(request, 'As categorias foram alteradas com sucesso!')
    return redirect (reverse('projects:project_detail', args=[project_pk]))

def set_categories(request, project_pk):
    project = get_object_or_404(Project, composite_pk=project_pk)
    form_categories = ProjectCategoriesForm(instance=project)
    return render(request,
            'projects/pages/project_categories.html',
            context={
                'form_categories': form_categories,
                'project_pk': project_pk,
            }
        )


@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
) 
class ProjectDetail(View):

    def render_template(self, user, project):
        return render(self.request, 'projects/pages/project_detail.html',
            context={
                'is_member': self.is_member(user, project),
                'project': project,
                'posts': self.get_posts(project),
                'user': user,
                'post_form': PostForm(),
                'members': self.get_members(project),
                'mods': self.get_mods(project),
                'solicitation': self.get_solicitation(project),
                'return_page': self.get_return_page(),
            })
    
    def get_return_page(self):
        next_param = self.request.GET.get('next', None)
        if not next_param:
            next_param = "/"
        return next_param
    
    def get_solicitation(self, project):
        return project.solicitation.all()

    def get_mods(self, project):
        return project.mods.all()
    
    def get_project(self, project_pk):
        project = get_object_or_404(Project, composite_pk=project_pk)
        return project
    
    def is_member(self, user, project):
        return project.members.filter(pk=user.pk).exists() or project.owner == user
    
    def get_members(self, project):
        return project.members.all()[:3]
    
    def get_posts(self, project):
        return Post.objects.filter(project=project).order_by("-created")
    
    def get(self, request, project_pk):
        project = self.get_project(project_pk)
        user = CustomUser.objects.get(pk=request.user.pk)
        return self.render_template(user, project)


@login_required(login_url='accounts:login', redirect_field_name='next')
def send_post(request):
    if not request.POST:
        raise Http404

    form = PostForm(request.POST)
    project_pk = request.POST.get('project_composite_pk')
    project = Project.objects.get(composite_pk=project_pk)


    post = form.save(commit=False)
    
    autor = CustomUser.objects.get(pk=request.user.pk)
    post.autor = autor
    post.project = project

    auto_id = Post.objects.filter(autor=autor, project=project)

    if auto_id:
        post.post_id = auto_id.last().post_id + 1
    else:
        post.post_id = 0

    post.save()

    messages.success(request, 'Sua postagem foi enviada.')
    return redirect (reverse('projects:project_detail', args=[project_pk]))


@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
) 
class PostDetail(View):

    def render_template(self, user, post):
        project = get_object_or_404(Project, composite_pk=post.project.composite_pk)
        return render(self.request, 'projects/pages/post_detail.html',
            context={
                'comments': self.get_comments(post),
                'post': post,
                'user': user,
                'project': project,
                'comment_form': CommentForm(),
                'mods': self.get_mods(project),
                'return_page': self.get_return_page(),
            })
    
    def get_return_page(self):
        next_param = self.request.GET.get('next', None)
        if not next_param:
            next_param = "/"
        return next_param
    
    def get_mods(self, project):
        return project.mods.all()
    
    def get_comments(self, post):
        return Comment.objects.filter(post=post).order_by("created")
    
    def get(self, request, post_pk):
        post = Post.objects.get(composite_pk=post_pk)
        user = CustomUser.objects.get(pk=request.user.pk)
        if not post.project.members.filter(pk=user.pk).exists() and not post.project.owner == user:
            raise Http404
        
        user = CustomUser.objects.get(pk=request.user.pk)
        return self.render_template(user, post)


@login_required(login_url='accounts:login', redirect_field_name='next')
def send_comment(request):
    if not request.POST:
        raise Http404

    form = CommentForm(request.POST)
    post_pk = request.POST.get('post_composite_pk')
    post = Post.objects.get(composite_pk=post_pk)


    comment = form.save(commit=False)
    
    autor = CustomUser.objects.get(pk=request.user.pk)
    comment.autor = autor
    comment.post = post

    auto_id = Comment.objects.filter(autor=autor, post=post)

    if auto_id:
        comment.comment_id = auto_id.last().comment_id + 1
    else:
        comment.comment_id = 0

    comment.save()

    messages.success(request, 'Seu Comentário foi enviado.')
    return redirect (reverse('projects:post_detail', args=[post_pk]))


@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
) 
class ProjectsList(View):

    def render_template(self, projects, category_active, recommendations):
        user = CustomUser.objects.get(pk=self.request.user.pk)
        categories = Category.objects.all()
        return render(
            self.request,
            'projects/pages/projects.html',
            context={
                'projects_page': True,
                'projects': projects,
                'user': user,
                'categories': categories,
                'category_active': category_active,
                'recommendations': recommendations,
            }
        )
    
    def get_recommendations(self):

projects/templates/projects/pages/project_categories.html
{% extends 'global/base.html' %}

{% block title %}Projeto{% endblock title %}

{% block content %}
<div class="container">
    <div class="my-2">
        <h1 class="mt-5 mb-1 text-center">Projeto</h1>
        <h3 class="mb-5 text-center">Selecione as Categorias do seu Projeto</h3>
        <div class="mx-auto w-50">
            <form></form>
                <form method="post" action="{% url 'projects:save_categories' project_pk %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form_categories %}
                        {{field}}
                    {% endfor %}
                    <div class="form-group-submit text-end my-4">
                        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-check"></i> Criar Projeto</button>
                    </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

projects/templates/projects/pages/project_detail.html
{% extends 'global/base.html' %}

{% block title %}Projeto{% endblock title %}

{% block content %}
<div class="container">
    <div class="my-3">
        <a href="{{return_page}}" class="btn-back"><i class="fa-solid fa-chevron-left"></i> Voltar</a>
    </div>
    {% if not project.status %}
    <div class="alert alert-danger" style="margin: 20px" role="alert">
        <p class="m-0"><b>Projeto Desativado</b></p>
        <p class="m-0">O projeto está inacessível e só você pode visualizá-lo. Ative o projeto na página de edição para deixá-lo visível novamente.</p>
    </div>
    {% endif %}
    <div class="row project-box justify-content-between align-items-center">
        <div class="col-5 text-center">
            <img class="profile-project-cover mb-2" src="{{ project.cover_photo.url }}" alt="Foto do Projeto">
            <h3>{{project.name}}</h3>
        </div>
        <div class="col-7 align-items-start align-self-stretch d-flex flex-column">
            <p class="project-detail-description my-2">{{project.description}}</p>
            <div class="d-flex">
            {% for category in project.categories.all %}
                <div class="col my-1 tag-project-detail"><p class="m-0"><i class="fa-solid fa-tag"></i> {{ category }}</p></div>
            {% endfor %}
            </div>
            <div class="align-self-end mt-auto d-flex">
                {% if project.owner == user or user in mods %}
                    <div class="btn-group">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Membros
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'projects:project_solicitation' project.composite_pk %}?next={{ request.path }}"><i class="fa-solid fa-envelope"></i> Solicitações</a></li>
                            <li><a href="{% url 'projects:members_list' project.composite_pk %}?next={{ request.path }}" class="dropdown-item"><i class="fa-solid fa-users"></i> Todos Membros</a></li>
                        </ul>
                    </div>
                {% elif is_member %}
                    <a href="{% url 'projects:members_list' project.composite_pk %}?next={{ request.path }}" class="mx-2 btn btn-primary"><i class="fa-solid fa-users"></i> Membros</a>
                {% endif %}
                {% if project.owner == user %}
                    <a class="btn btn-primary mx-2 " href="{% url 'projects:project_edit' project.composite_pk %}?next={{ request.path }}"><i class="fa-solid fa-pen-to-square"></i> Editar Projeto</a>
                {% elif is_member %}
                <form></form>
                <form id="formLeaveProject" class="mx-2" action="{% url 'projects:project_leave' %}" method='POST'>
                    {% csrf_token %}
                    <input type="hidden" name="project_composite_pk" value="{{project.composite_pk}}">
                    <button id="btnConfirmLeave" type="submit" class="btn btn-outline-danger"><i class="fa-solid fa-right-from-bracket"></i> Sair</button>
                <form>
                {% elif user in solicitation %}
                <form></form>
                <form class="mx-2" action="{% url 'projects:solicitation_remove' %}" method='POST'>
                    {% csrf_token %}
                    <input type="hidden" name="project_composite_pk" value="{{project.composite_pk}}">
                    <button type="submit" class="btn btn-danger"><i class="fa-solid fa-xmark"></i> Remover Solicitação</button>
                <form>   
                {% else %}
                <form></form>
                <form class="mx-2" action="{% url 'projects:solicitation_add' %}" method='POST'>
                    {% csrf_token %}
                    <input type="hidden" name="project_composite_pk" value="{{project.composite_pk}}">
                    <button type="submit" class="btn btn-primary">Solicitar Entrada <i class="fa-solid fa-right-to-bracket"></i> </button>
                <form>
                {% endif %}
            </div>
        </div>
    </div>
    <hr>
    {% if is_member %}
    <div>
        <form></form>
        <form class="post-form" action="{% url 'projects:send_post' %}"  method="POST">
            {% csrf_token %}
            <input type="hidden" name="project_composite_pk" value="{{project.composite_pk}}">
            {% for field in post_form %}
                <div class="my-3 d-flex">
                    <div>
                        <img class="post-img" src="{{ user.profile_picture.url }}" alt="Foto de perfil">
                    </div>
                    {{field}}
                </div>
            {% endfor %}
            <div class="form-group-submit text-end my-4">
                <button class="btn btn-secondary rounded-btn" type="submit"><i class="fa-solid fa-paper-plane"></i></button>
            </div>
        </form>
    </div>
    <hr>
    {% endif %}
    <div>
        {% if is_member %}
        <h4>Postagens</h4>
        {% for post in posts %}
            <div class="my-5" data-aos="fade-up" data-aos-duration="800">
                <div class="d-flex">
                    <div class="pr-2 col-1">
                        {% if post.autor == user %}
                            <img class="post-img" src="{{ post.autor.profile_picture.url }}" alt="Foto de perfil">
                        {% else %}
                            <a href="{% url 'accounts:view_profile' post.autor.cpf %}?next={{ request.path }}"><img class="post-img" src="{{ post.autor.profile_picture.url }}" alt="Foto de perfil"></a>
                        {% endif %}
                    </div>
                    <div class=col-10>
                        {% if post.autor == user %}
                            <h5 class="m-0">{{post.autor.first_name}} {{post.autor.last_name}}</h5>
                        {% else %}
                            <a href="{% url 'accounts:view_profile' post.autor.cpf %}?next={{ request.path }}"><h5 class="m-0">{{post.autor.first_name}} {{post.autor.last_name}}</h5></a>
                        {% endif %}
                        <div>
                            {% if project.owner == post.autor %}
                                Dono
                            {% elif post.autor in mods %}
                                Moderador
                            {% else %}
                                Membro
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-1">
                        {% if project.owner == user or user in mods or user == post.autor%}
                            <div class="btn-group dropstart">
                                <div type="button" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-solid fa-ellipsis-vertical"></i>
                                </div>
                                <ul class="dropdown-menu">
                                    <li>
                                        <form></form>
                                        <form id="{{post.composite_pk}}" class="mx-2" action="{% url 'projects:post_delete' %}" method='POST'>
                                            {% csrf_token %}
                                            <input type="hidden" name="post_composite_pk" value="{{post.composite_pk}}">
                                            <button type="submit" class="btn btn-link dropdown-item btn-confirm-delete"><i class="fa-solid fa-trash"></i> Excluir Postagem</button>
                                        <form>
                                    </li>
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="my-2">
                    <p>{{post.text}}</p>
                    <div class="post-created">
                        {{post.created}}
                    </div>
                </div>
                
                <div class="footer-post">
                    <i class="fa-regular fa-comment"></i> <a href="{% url 'projects:post_detail' post.composite_pk %}?next={{ request.path }}">Comentários</a>
                </div>
                <hr>
            </div>
            <div class="modal fade" id="confirmDeletePost{{post.composite_pk}}Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Tem certeza que deseja excluir a Postagem?</h5>
                    </div>
                    <div class="modal-body">
                      Ao excluir uma postagem todos comentários relacionados são excluídos. Essa ação não pode ser desfeita.
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                      <button type="button" class="btn btn-danger btn-confirm">Excluir</button>
                    </div>
                  </div>
                </div>
            </div>
            {% empty %}
            <h5 class="text-center my-5">Ainda não há postagens nesse projeto</h5>
            {% endfor %}
        {% else %}
        <div class="my-5 row" data-aos="fade-up" data-aos-duration="800">
            <div class="col-8">
                <h4>Postagens</h4>
                <h1 class="text-center"><i class="fa-solid fa-lock"></i></h1>
                <h5 class="text-center">Torne-se membro para<br>visualizar e postar</h5>
            </div>
            <div class="col-4 text-left">
                <a class="scale-hover" href="{% url 'projects:members_list' project.composite_pk %}?next={{ request.path }}"><h4 class="mb-3"><i class="fa-solid fa-users"></i> Membros</h4></a>
                <div class="row justify-content-center">
                    <div class="col-2">
                        <img class="post-img" src="{{ project.owner.profile_picture.url }}" alt="Foto de perfil">
                    </div>
                    <div class="col-10">
                        <h5 class="m-0">
                            {{project.owner.first_name}} {{project.owner.last_name}}
                        </h5>
                        <p class="m-0">Dono</p>
                    </div>
                </div>
                {% for member in members %}
                <hr>
                <div class="row justify-content-center">
                    <div class="col-2">
                        <img class="post-img" src="{{ member.profile_picture.url }}" alt="Foto de perfil">
                    </div>
                    <div class="col-10">
                        <h5 class="m-0">
                            {{member.first_name}} {{member.last_name}}
                        </h5>
                        <p class="m-0">
                            {% if member in mods %}
                                Moderador
                            {% else %}
                                Membro
                            {% endif %}
                        </p>
                    </div>
                </div>      
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>

</div>
  
  <div class="modal fade" id="confirmLeaveModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Tem certeza que seja sair do Projeto?</h5>
        </div>
        <div class="modal-body">
          Você não poderá mais visualizar ou interagir com as postagens do Projeto.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button id="modalButtonLeave" type="button" class="btn btn-danger">Sair</button>
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}