abrace/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout', views.logout_view, name='logout'),
    path('profile/', views.ProfileDetail.as_view(), name='profile'),
    path('profile/edit', views.ProfileEdit.as_view(), name='profile_edit'),
    path('profile/delete', views.profile_delete, name='profile_delete'),
    path('profile/edit/categories', views.save_categories, name='save_categories'),
    path('profile/projects', views.MyProjectsList.as_view(), name='my_projects'),
    path('profile/reviews', views.review_view, name='profile_reviews'),
    path('profile/view/<str:cpf>/', views.ViewProfile.as_view(), name='view_profile'),
    path('profile/view/<str:cpf>/filter/<str:role>/', views.ViewProfile.as_view(), name='view_profile_projects_filter'),
    path('review/<str:reviewed_pk>/<str:project_pk>', views.ReviewCreateView.as_view(), name='review'),
    path('profile/projects/filter/<str:role>/', views.MyProjectsList.as_view(), name='my_projects_filter'),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.home, name='home'),
    path('projects', views.ProjectsList.as_view(), name='projects'),
    path('filter/category/<str:category>/', views.ProjectsList.as_view(), name='projects_filter'),
    path('project/new', views.ProjectDashboard.as_view(), name='project_new'),
    path('project/edit/categories/set/<str:project_pk>', views.set_categories, name='set_categories'),
    path('project/edit/categories/<str:project_pk>', views.save_categories, name='save_categories'),
    path('project/edit/<str:project_pk>', views.ProjectDashboard.as_view(), name='project_edit'), 
    path('project/detail/<str:project_pk>', views.ProjectDetail.as_view(), name='project_detail'),
    path('project/post/send', views.send_post, name='send_post'),
    path('project/comment/send', views.send_comment, name='send_comment'),
    path('project/post/detail/<str:post_pk>', views.PostDetail.as_view(), name='post_detail'),
    path('project/leave', views.leave_project, name='project_leave'),
    path('project/delete', views.delete_project, name='project_delete'),
    path('project/members/<str:project_pk>', views.MembersList.as_view(), name='members_list'),
    path('project/mod/add', views.add_mod, name='mod_add'),
    path('project/mod/remove', views.remove_mod, name='mod_remove'),
    path('project/member/remove', views.remove_member, name='member_remove'),
    path('project/post/delete', views.delete_post, name='post_delete'),
    path('project/solicitation/add', views.add_solicitation, name='solicitation_add'),
    path('project/solicitation/remove', views.remove_solicitation, name='solicitation_remove'),
    path('project/solicitation/accept', views.accept_solicitation, name='solicitation_accept'),
    path('project/solicitation/reject', views.reject_solicitation, name='solicitation_reject'),
    path('project/solicitation/<str:project_pk>', views.Solicitation.as_view(), name='project_solicitation'),
    path('project/deactivate/<str:project_pk>', views.deactivate, name='deactivate'),
    path('project/search/', views.search_project, name='search_project'),
]

accounts/forms/edit_profile.py
from django import forms
from collections import defaultdict
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from accounts.models import CustomUser
from datetime import date, timedelta


class EditProfileForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['profile_picture'].widget.attrs.update({'class': 'form-control-file d-none', 'required':'required', 'id': 'flImage'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'required':'required'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'required':'required'})
        self.fields['city'].widget.attrs.update({'class': 'form-control', 'required':'required'})
        self.fields['state'].widget.attrs.update({'class': 'form-control', 'required':'required'})
        self.fields['country'].widget.attrs.update({'class': 'form-control', 'required':'required'})
        self.fields['zipcode'].widget.attrs.update({'class': 'form-control cep-input', 'required':'required'})
        self.fields['birth_date'] = forms.DateField(
            label='Data de nascimento',
            widget=forms.DateInput(format=('%Y-%m-%d'),
                                   attrs={'class': 'form-control',
                                          'required': 'required',
                                          'type': 'date'
                                          })
        )
        
        self._my_errors = defaultdict(list)

    class Meta:
        model = CustomUser
        fields = [
            'profile_picture',
            'first_name',
            'last_name',
            'zipcode',
            'city',
            'state',
            'country',
            'birth_date',
        ]
        labels = {
            'profile_picture': 'Foto de Perfil',
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'city': 'Cidade',
            'state': 'Estado',
            'country': 'País',
            'zipcode': 'CEP',
            'birth_date': 'Data de nascimento',
        }



    def clean_first_name(self):
        data = self.cleaned_data.get('first_name').strip()

        if len(data) < 1:
            raise ValidationError(
                'Este campo não pode estar vazio',
                code='required',
            )

        return data

    def clean_last_name(self):
        data = self.cleaned_data.get('last_name').strip()

        if len(data) < 1:
            raise ValidationError(
                'Este campo não pode estar vazio',
                code='required',
            )

        return data
    
    def clean_birth_date(self):
        birth_date = self.cleaned_data.get('birth_date')
        min_birth_date = date.today() - timedelta(days=150*365)  

        if birth_date >= date.today() or birth_date <= min_birth_date:
            raise ValidationError(
                'Digite uma data de nascimento válida.',
                code='invalid',
            )

        return birth_date
    

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)

        if self._my_errors:
            raise ValidationError(self._my_errors)

accounts/forms/login.py
from django import forms


class LoginForm(forms.Form):

    email = forms.CharField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control', 'required': 'required'}),
        error_messages={'required': 'Este campo não pode estar vazio'}
    )
    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'required': 'required'}),
        error_messages={'required': 'Este campo não pode estar vazio'}
    )

accounts/views.py
from django.shortcuts import redirect, render
from .forms import RegisterForm, LoginForm, EditProfileForm, ProfileCategoriesForm, ReviewForm
from django.contrib.auth.models import User
from django.http import Http404
from .models import CustomUser, Category, Review
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.views import View
from projects.models import Project
from django.db.models import Q
from django.shortcuts import get_object_or_404

def register_view(request):

    register_form_data = request.session.get('register_form_data')
    form = RegisterForm(register_form_data)

    return render(request, 'accounts/pages/register.html', {
        'form': form,
    })

def register_create(request):

    if not request.POST:
        raise Http404

    POST = request.POST

    request.session['register_form_data'] = POST

    form = RegisterForm(POST, request.FILES)

    if form.is_valid():

        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        del (request.session['register_form_data'])
        messages.success(request, 'A conta foi criada com sucesso')

        authenticated_user = authenticate(
            username=user.email,
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            login(request, authenticated_user)
        
            return redirect(reverse('accounts:profile'))
    
    messages.error(request, 'Erro ao criar conta')

    return redirect('accounts:register')

def login_view(request):

    login_form_data = request.session.get('login_form_data')
    form = LoginForm(login_form_data)

    return render(request, 'accounts/pages/login.html', {
        'form': form,
    })

def login_create(request):

    if not request.POST:
        raise Http404

    POST = request.POST

    request.session['login_form_data'] = POST

    form = LoginForm(POST)

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('email', ''),
            password=form.cleaned_data.get('password', ''),
        )

        if authenticated_user is not None:
            login(request, authenticated_user)
            if request.session.get('login_form_data') is not None:
                del (request.session['login_form_data'])
                return redirect(reverse('projects:projects'))

        else:
            messages.error(request, 'Senha ou usuário inválido')

    return redirect(reverse('accounts:login'))

@login_required(login_url='accounts:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return Http404

    logout(request)
    return redirect(reverse('accounts:login'))


@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
)
class ProfileDetail(View):

    def render_template(self, profile, categories):
        return render(
            self.request,
            'accounts/pages/profile.html',
            context={
                'profile': profile,
                'profile_page': True,
                'profile_tab': True,
                'categories': categories,
            }
        )

    def get(self, request):

        profile = CustomUser.objects.get(pk=request.user.pk)
        categories = Category.objects.all()
        return self.render_template(profile, categories)

@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
) 
class ProfileEdit(View):

    def render_template(self, form, categories, profile):
        return render(
            self.request,
            'accounts/pages/edit_profile.html',
            context={
                'form': form,
                'form_categories': categories,
                'profile_page': True,
                'profile_tab': True,
                'user': profile,
                'return_page': self.get_return_page(),
            }
        )
    
    def get_return_page(self):
        next_param = self.request.GET.get('next', None)
        if not next_param:
            next_param = "/"
        return next_param

    def get(self, request):

        profile = CustomUser.objects.get(pk=request.user.pk)
        form = EditProfileForm(instance=profile)
        categories = ProfileCategoriesForm(instance=profile)

        return self.render_template(form, categories, profile)

    def post(self, request):

        profile = CustomUser.objects.get(pk=request.user.pk)

        form = EditProfileForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=profile, 
        )

        if form.is_valid():

            form.save()

            messages.success(request, 'O perfil foi alterado com sucesso!')
            return redirect(reverse('accounts:profile'))

        categories = ProfileCategoriesForm(instance=profile)
        messages.error(request, 'Há campos incorretos no formulário')
        return self.render_template(form, categories, profile)

@login_required(login_url='accounts:login', redirect_field_name='next')
def save_categories(request):
    if not request.POST:
        raise Http404

    profile = CustomUser.objects.get(pk=request.user.pk)

    form = ProfileCategoriesForm(
            data=request.POST or None,
            instance=profile, 
    )

    if form.is_valid():
        form.save()
    else:
        profile.categories.set('')
        profile.save()

    messages.success(request, 'As preferências foram alteradas com sucesso!')
    return redirect(reverse('accounts:profile'))


@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
)
class MyProjectsList(View):

    def render_template(self, projects, profile, role):
        return render(
            self.request,
            'accounts/pages/my_projects.html',
            context={
                'projects': projects,
                'profile_page': True,
                'project_tab': True,
                'profile': profile,
                'role': role,
            }
        )

    def get(self, request, role=None):

        profile = CustomUser.objects.get(pk=request.user.pk)

        if role:
            if role == 'Dono':
                projects = Project.objects.filter(owner=profile)
            elif role == 'Moderador':
                projects = Project.objects.filter(mods=profile, status=True)
            else:
                projects = Project.objects.filter(members=profile, status=True)
        else:
            projects_owner = Project.objects.filter(owner=profile)
            projects_members = Project.objects.filter(members=profile, status=True)
            projects = projects_owner.union(projects_members)

        return self.render_template(projects, profile, role)

@login_required(login_url='accounts:login', redirect_field_name='next')
def review_view(request):
    profile = get_object_or_404(CustomUser, pk=request.user.pk)
    reviews = Review.objects.filter(reviewed_user=profile)

    return render(request, 'accounts/pages/reviews.html', {
        'profile': profile,
        'reviews': reviews,
        'profile_page': True,
        'review_tab': True,
    })
    
@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
) 
class ReviewCreateView(View):

    def render_template(self, form, reviewed_user, project, author_user):
        return render(self.request, 'accounts/pages/review_create.html', {
            'form': form,
            'reviewed_user': reviewed_user,
            'project': project,
            'user': author_user,
            'return_page': self.get_return_page(),
        })
    
    def get_return_page(self):
        next_param = self.request.GET.get('next', None)
        if not next_param:
            next_param = "/"
        return next_param
    
    def get(self, request, reviewed_pk, project_pk):

        author_user = CustomUser.objects.get(pk=request.user.pk)
        reviewed_user = CustomUser.objects.get(pk=reviewed_pk)
        project = Project.objects.get(composite_pk=project_pk)
        form = ReviewForm()

        return self.render_template(form, reviewed_user, project, author_user)

    def post(self, request, reviewed_pk, project_pk):

        form = ReviewForm(request.POST)
        project_pk = request.POST.get('project_composite_pk')
        project = Project.objects.get(composite_pk=project_pk)

        review = form.save(commit=False)

        author_user = CustomUser.objects.get(pk=request.user.pk)
        reviewed_user = CustomUser.objects.get(cpf=request.POST.get('reviewed_user_cpf'))

        review.author_user = author_user
        review.reviewed_user = reviewed_user
        review.project = project

        auto_id = Review.objects.filter(reviewed_user=reviewed_user, project=project)

        if auto_id:
            review.review_id = auto_id.last().review_id + 1
        else:
            review.review_id = 0

        review.save()

        messages.success(request, 'Sua avaliação foi enviada.')
        return redirect (reverse('projects:members_list', args=[project_pk]))

@method_decorator(
    login_required(login_url='accounts:login', redirect_field_name='next'),
    name='dispatch'
)
class ViewProfile(View):

    def render_template(self, profile, categories, projects, role):
        reviews = Review.objects.filter(reviewed_user=profile)
        user = CustomUser.objects.get(pk=self.request.user.pk)
        return render(
            self.request,
            'accounts/pages/view_profile.html',
            context={
                'profile': profile,
                'profile_tab': True,

accounts/templates/accounts/pages/edit_profile.html
{% extends 'global/base.html' %}
{% load static %}
{% block title %}Editar Perfil{% endblock title %}

{% block content %}
<div class="container">
    {% include 'accounts/partials/nav-profile.html' %}
        <div class="my-3">
            <a href="{{return_page}}" class="btn-back"><i class="fa-solid fa-chevron-left"></i> Voltar</a>
        </div>
        <div class="row my-2 profile-detail">
            <div class="col-7">
                <form></form>
                <form action="{% url 'accounts:profile_edit' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="my-3">
                            {% if field.label == 'Foto de Perfil' %}
                            <div class="max-width-profile text-center">
                                <div class="imageContainer">
                                    <img class="imgPhoto-profile" src="{{user.profile_picture.url}}" alt="Selecione uma imagem" id="imgPhoto">
                                </div>
                            </div>
                            <input class="d-none" type="file" name="{{ form.profile_picture.name }}" id="{{ form.profile_picture.id_for_label }}" value="{{ user.profile_picture.url }}"/>
                            {% else %}
                                <label class="form-label" for="{{ field.id_for_label }}">{{field.label}}</label>
                                {{field}}
                            {% endif %}
                            <div class="error-list">
                                {{field.errors}}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group-submit text-center my-4" style="width: 80%">
                        <button class="btn btn-primary" type="submit">Salvar</button>
                    </div>
                </form>
            </div>
            <div class="col-4">
                <form method="post" action="{% url 'accounts:save_categories' %}" enctype="multipart/form-data">
                    <label class="d-block form-label text-center">Categorias</label>
                    <div class="category-box category-box-edit">
                        {% csrf_token %}
                        {{ form_categories }}
                    </div>
                    <div class="form-group-submit text-center my-4">
                        <button class="btn btn-primary" type="submit">Salvar preferências</button>
                    </div>
                </form>
            </div>
            <div class="my-5 text-center">
                <button data-bs-toggle="modal" data-bs-target="#confirmDeleteAccountModal" class="btn btn-danger">Excluir Conta</button>
            </div>
        </div>

</div>

<div class="modal fade" id="confirmDeleteAccountModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Confirme a Exclusão</h5>
            </div>
            <div class="modal-body">
                <p>Isso excluirá todos os dados da sua conta e todos os projetos que você criou. Essa ação é irreversível.</p>
                <form action="{% url 'accounts:profile_delete' %}" method="post" >
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="password">Para confirmar a exclusão digite sua senha:</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <div class="text-center my-3">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

accounts/templates/accounts/pages/my_projects.html
{% extends 'global/base.html' %}

{% block title %}Perfil - Projetos{% endblock title %}

{% block content %}
<div class="container">
    {% include 'accounts/partials/nav-profile.html' %}
    <div class="d-flex justify-content-between align-items-center my-2">
        <div>
            <select class="form-select" id="filterSelectProfile">
                <option {% if not role %}selected{% endif %} value="Todos">Todos</option>
                <option {% if role == 'Dono' %}selected{% endif %} value="Dono">Dono</option>
                <option {% if role == 'Moderador' %}selected{% endif %} value="Moderador">Moderador</option>
                <option {% if role == 'Membro' %}selected{% endif %} value="Membro">Membro</option>
            </select>
        </div>
        <div>
            <a class="btn btn-outline-primary" href="{% url 'projects:project_new' %}?next={{ request.path }}"><i class="fa-solid fa-plus"></i> Criar Projeto</a>
        </div>
    </div>
    <div class="row justify-content-start my-1 h-100">
    {% for project in projects %}
        <div class="mx-1 my-3 profile-project-box" data-aos="fade-up" data-aos-duration="800">
            <a href="{% url 'projects:project_detail' project.composite_pk %}?next={{ request.path }}">
                <img class="profile-project-cover" src="{{ project.cover_photo.url }}" alt="Capa do Projeto">
                <h3 class="mt-3">Projeto - {{project.name}}</h3>
                <p class="tags">
                    {% if project.categories.all %}<i class="fa-solid fa-tags"></i> {% endif %}
                    {% for category in project.categories.all %}
                        {{category.title}}; 
                    {% endfor %}
                </p>
                {% if profile == project.owner %}
                    <p class="small-text"><i class="fa-solid fa-circle owner"></i> Dono </p>
                {% elif profile in project.mods.all %}
                    <p class="small-text"><i class="fa-solid fa-circle mod"></i> moderador</p>
                {% else %}
                    <p class="small-text"><i class="fa-solid fa-circle member"></i> Membro</p>
                {% endif %}

                {% if not project.status %}
                    <p class="text-center text-red"><b>Projeto Desativado</b></p>
                {% endif %}
            </a>
        </div>
    {% empty %} 
        <h4 class="text-center mt-5">
            Nenhum projeto encontrado
        </h4>
        <h5 class="text-center mb-5">Tente criar um novo projeto ou entrar em um projeto já existente</h5>
    {% endfor %}
    </div>

</div>

{% endblock content %}

accounts/templates/accounts/pages/view_profile.html
{% extends 'global/base.html' %}

{% block title %}{{profile.first_name}} - Perfil{% endblock title %}

{% block content %}
<div class="container">
    <div class="my-3">
    <a href="{{return_page}}" class="btn-back"><i class="fa-solid fa-chevron-left"></i> Voltar</a>
    </div>
    <div class="text-center mx-auto w-50 row align-items-center justify-content-between my-5">
        <img class="profile-img" src="{{ profile.profile_picture.url }}" alt="Imagem de Perfil">
        <div class="col-7">
            <h2>{{profile.first_name}} {{profile.last_name}}</h2>
            <p class="my-0"><i class="fa-solid fa-location-dot"></i> {{profile.city}}, {{profile.state}}</p>
            <p class="my-0"><i class="fa-solid fa-envelope"></i> {{profile.email}}</p>
            <div class="m-0 row">
                {% for category in profile.categories.all %}
                <div class="col my-1 tag-bg"><p class="m-0"><i class="fa-solid fa-tag"></i> {{ category }}</p></div>
                {% endfor %}
            </div>
        </div>
    </div>
    <hr>
    <div class="row my-5 justify-content-between" data-aos="fade-up" data-aos-duration="800">
        <div class="col-6">
            <h5>Avaliações</h5>
            {% for review in reviews %}
            <div class="review-box row my-5">
                <div class="col-2 text-center">
                    <a {% if not user == review.author_user %}href="{% url 'accounts:view_profile' review.author_user.cpf %}?next={{ request.path }}"{% endif %}>
                        <img class="review-profile-img" src="{{ review.author_user.profile_picture.url }}" alt="Imagem de Autor">
                        
                    </a>
                </div>
                <div class="col-9">
                    <div class="d-flex justify-content-between mb-2">
                        <div class="review-project-name review-project-profile-name">
                            <span>{{review.author_user.first_name}}</span> - {{review.project}}
                        </div>
                        <div class="review-project-name">
                            {% if review.review_value == 1 %}
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                            {% elif review.review_value == 2 %}
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                            {% elif review.review_value == 3 %}
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                            {% elif review.review_value == 4 %}
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-gray"></i>
                            {% elif review.review_value == 5 %}
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                                <i class="fa-solid fa-star star-yellow"></i>
                            {% endif %}                        
                        </div>
                    </div>
                    <div class="review-body review-profile-body">
                        <p>{{review.review_body}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-center mt-5">
                O usuário ainda não possui avaliações
            </p>
            {% endfor %}
        </div>
        <div class="col-6">
            <div class="d-flex justify-content-between align-items-center">
                <h5>Projetos</h5>
                <div>
                    <select class="form-select" id="filterSelectProfileView">
                        <option {% if not role %}selected{% endif %} value="Todos">Todos</option>
                        <option {% if role == 'Dono' %}selected{% endif %} value="Dono">Dono</option>
                        <option {% if role == 'Moderador' %}selected{% endif %} value="Moderador">Moderador</option>
                        <option {% if role == 'Membro' %}selected{% endif %} value="Membro">Membro</option>
                    </select>
                </div>
            </div>
            <div class="row justify-content-between">
            {% for project in projects %}
                <div class="my-3 view-profile-project-box profile-project-box col-6">
                    <a href="{% url 'projects:project_detail' project.composite_pk %}?next={{ request.path }}">
                        <img class="profile-project-cover" src="{{ project.cover_photo.url }}" alt="Capa do Projeto">
                        <h3 class="mt-3">Projeto - {{project.name}}</h3>
                        <p class="tags">
                            {% if project.categories.all %}<i class="fa-solid fa-tags"></i> {% endif %}
                            {% for category in project.categories.all %}
                                {{category.title}}{% if not forloop.last %};{% endif %} 
                            {% endfor %}
                        </p>
                        {% if profile == project.owner %}
                            <p class="small-text"><i class="fa-solid fa-circle owner"></i> Dono </p>
                        {% elif profile in project.mods.all %}
                            <p class="small-text"><i class="fa-solid fa-circle mod"></i> moderador</p>
                        {% else %}
                            <p class="small-text"><i class="fa-solid fa-circle member"></i> Membro</p>
                        {% endif %}
                    </a>
                </div>
            {% empty %} 
                <p class="text-center mt-5">
                    Não foram encontrados projetos
                </p>
            {% endfor %}
            </div>
        </div>
    </div>

    

</div>

{% endblock content %}